name: Deploy Backend to EC2 with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/gemini-chat-backend
            
            git pull
            
            docker build -t gemini-backend .
            
            docker stop gemini-backend-prod || true
            docker rm gemini-backend-prod || true
            
            docker run -d --restart always --network=host --name gemini-backend-prod gemini-backend