name: Deploy Backend to Dev Server

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/pjhpoi66/gemini-chat/gemini-chat-backend
            
            git pull
            
            docker stop gemini-backend-prod || true
            docker rm gemini-backend-prod || true
            docker rmi gemini-backend || true
            
            docker image prune -a -f
            
            docker build --no-cache -t gemini-backend .
            
            docker run -d --restart always --network=host --name gemini-backend-prod gemini-backend